### ISSUE TITLE
Deque reusable cells in cellForRowAtIndexPath

### ISSUE THREAD

**Issue by rainypixels** [krzyzanowskim/GeneratedResults-UITableView#1]
You probably want to call `dequeReusableCellForIndexPath` on the tableView on [this line](https://github.com/krzyzanowskim/GeneratedResults-UITableView/blob/master/GeneratedResults/ViewController.swift#L74) as opposed to creating a new table view cell each time, right?

Love the architecture, btw. I implemented something similar, but your generics approach is more elegant than what I came up with. :)

**Comment by krzyzanowskim** [comment]
I'd need cell view in IB in the first place ;-)

**Comment by krzyzanowskim** [comment]
btw. you can prepare Pull Request if you want ;-)

**Comment by rainypixels** [comment]
OK, done. :-)
